Nodocwrite
cenw-wscoe/sgdc-cdts pull request #32
Opened 2022-07-21 21:32 UTC by plup2

2022-07-28 18:44 UTC, j-paquette requested changes

2022-07-28 18:44 UTC, j-paquette commented on docs/guide-decl-gcintranet-fr.html
> +						<li><a href="#GCIntranet_.2F_version_.2F_default">run</a></li>
@plup2 href should point to `<li><a href="#GCIntranet_.2F_run_.2F_default">run</a></li>`

2022-07-28 18:44 UTC, j-paquette commented on docs/internet-decl-fr.html
> +				<li>Le contrôle de version signifie que vous ne recevrez PAS de mise à jour automatique de la BOEW. Vous mettrez en place une «&#160;version&#160;» dans votre actif Web et ajouterez un mécanisme
@plup2: href should point to: `<a href="./templates-fr.html">`

2022-07-28 21:17 UTC, plup2 commented on docs/guide-decl-gcintranet-fr.html
> +						<li><a href="#GCIntranet_.2F_version_.2F_default">run</a></li>
Done

2022-07-28 21:17 UTC, plup2 commented on docs/internet-decl-fr.html
> +				<li>Le contrôle de version signifie que vous ne recevrez PAS de mise à jour automatique de la BOEW. Vous mettrez en place une «&#160;version&#160;» dans votre actif Web et ajouterez un mécanisme
Done

2022-07-29 15:33 UTC, j-paquette approved these changes

2022-07-29 15:33 UTC, merged